### ISSUE TITLE
problems with `glmnet` learner in `cor_thresh` 

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#100]
The current build fails in `cor_thresh` running `Run_Threshold_analysis.R`

```r
[1] "Day29bindSpike"
[1] "Running analysis for threshold: 3.221"
Failed on Lrnr_glmnet_NULL_deviance_10_1_100_TRUE
Error in if (!all(o)) { : missing value where TRUE/FALSE needed
> traceback()
10: stop(first_error$value)
9: self$compute_step()
8: scheduler$compute()
7: delayed_fit$compute(job_type = sl3_delayed_job_type(), progress = verbose)
6: lrnr_Delta$train(tasks_Delta$train_u) at tmleThresh.R#290
5: get_preds_TSM(task_list, lrnr_A, lrnr_Y, lrnr_Delta) at tmleThresh.R#45
4: thresholdTMLE(data_full, node_list, thresholds = thresholds, 
       biased_sampling_strata = "grp", biased_sampling_indicator = "TwophasesampInd", 
       lrnr_A = lrnr, lrnr_Y = lrnr, lrnr_Delta = Lrnr_glmnet$new()) at #12
3: withCallingHandlers(expr, warning = function(w) if (inherits(w, 
       classes)) tryInvokeRestart("muffleWarning"))
2: suppressWarnings(thresholdTMLE(data_full, node_list, thresholds = thresholds, 
       biased_sampling_strata = "grp", biased_sampling_indicator = "TwophasesampInd", 
       lrnr_A = lrnr, lrnr_Y = lrnr, lrnr_Delta = Lrnr_glmnet$new())) at #12
1: run_threshold_analysis(marker)
```

_Originally posted by @benkeser in https://github.com/CoVPN/correlates_reporting/issues/96#issuecomment-790758525_

**Comment by Larsvanderlaan** [comment]
Hi David,

Is this using the latest version of the threshold code? Or is this based on the code from before yesterday's pull-request?

If the latter, I believe this error is caused because the synthetic dataset "practice_data.csv" generates a few NA weights (variable "wt") for individuals in the "TwophasesampInd ==1 & Trt == 1 & Bserostatus == 0 & Perprotocol == 1" subgroup, which is the subgroup I run the learners on. The NA weights seem to be unexpected behavior. I see also that there is another variable in the dataset "wt.2" that does not have these NA weight values.  These two weight variables seem to be different, and "wt.2" is not documented in the clean_data "ReadMe" file. The NA weights were not present during my first pull request and they appeared when I ran my analysis in the latest version of the COVPN/correlates_reporting github yesterday afternoon (before I made any changes). Is this by chance a bug in the synthetic data generation?

The latest version of the code from yesterday's pull-request should have allowed the threshold analysis to run without error (sloppily by dropping the individuals with NA weights and outputting a warning).  I thought this was maybe an issue with my local computer. In hindsight, I should have contacted you about this.

Run R code:
table(is.na(practice_data[practice_data$TwophasesampInd ==1 & practice_data$Trt == 1 & practice_data$Bserostatus == 0 & practice_data$Perprotocol == 1, "wt"]))
output:
FALSE  TRUE 
  972     3 

Run R code:
table(is.na(practice_data[practice_data$TwophasesampInd ==1 & practice_data$Trt == 1 & practice_data$Bserostatus == 0 & practice_data$Perprotocol == 1, "wt.2"]))
output:
FALSE  TRUE 
  975     0 

The patient ID's with missing weights are 191, 254, 5930


Best,
Lars

**Comment by benkeser** [comment]
Thanks, yes, the `NA` weights were introduced by @youyifong and have caused a lot of problems. @youyifong , could you advise on the best action? In the graphics folders, I've just been setting the missing values to 0, which logically makes sense to me. But maybe I'm overlooking something.

**Comment by youyifong** [comment]
In the case of cor_coxph, the trouble it caused is a good thing because it
exposed a bug in the original code.

Subsetting by !is.na(wt) if needed is the best course of action I think
since dat.mock is usually not the population of interest.

Let's discuss this more tomorrow.

**Comment by benkeser** [comment]
@Larsvanderlaan can you join our call tomorrow to get on the same page about this?

**Comment by Larsvanderlaan** [comment]
Hi David,
Thank you for your help. It would be great to join the call. Could you message me the meeting time/zoom link?
I do have two Visiting Days tomorrow but I will try my best to attend the call.

**Comment by benkeser** [comment]
Sent meeting info to your berkeley address.

**Comment by youyifong** [comment]
Hi Lars, thanks for trying to join the call tomorrow. Sorry for not
informing you of this earlier. To give some context on this recent change
in data preprocessing, I realized that in the previous definition of wt, I
had given everybody a weight, even the people not in the intended
population. The new line is the line that ends with NA. Alternatively, we
can set it to 0, as David suggested.
Best, Youyi

wts_table <- with(
  subset(dat_proc, Perprotocol == 1 & EventTimePrimaryD57>=7),
  table(Wstratum, TwophasesampInd)
)
wts_norm <- rowSums(wts_table) / wts_table[, 2]
dat_proc$wt <- wts_norm[dat_proc$Wstratum]
dat_proc$wt[!with(dat_proc, Perprotocol == 1 & EventTimePrimaryD57>=7)] <-
NA

wts_table2 <- with(
  subset(dat_proc, EventTimePrimaryD29>=14 & Perprotocol == 1 |
EventTimePrimaryD29>=7 & EventTimePrimaryD29<=13 & Fullvaccine==1),
  table(Wstratum, TwophasesampInd)
)
wts_norm2 <- rowSums(wts_table2) / wts_table2[, 2]
dat_proc$wt.2 <- wts_norm2[dat_proc$Wstratum]
dat_proc$wt.2[!with(dat_proc, EventTimePrimaryD29>=14 & Perprotocol == 1 |
EventTimePrimaryD29>=7 & EventTimePrimaryD29<=13 & Fullvaccine==1)] <- NA

**Comment by benkeser** [comment]
Moving conversation to #114
