### ISSUE TITLE
tagging compiled reports with a build ID

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#115]
@nhejazi @thebioengineer 
It occurs to me that we may want to modify the deploy script for travis builds. Right now, it just clears out the entire gh-pages branch and puts the compiled reports there and pushes back.

Maybe better would be to have a folder for `master` builds and a folder for PR builds that includes reports where the name includes the PR number or the travis build ID or something. That way, submitters could track down their actual report built from their PR without the hassle of going through commits. 

What do you think? Worth the few lines of bash in the travis file?

**Comment by thebioengineer** [comment]
Yeah. Clearing out the entire gh_pages after each build is less than ideal. Could Travis just hold the artifacts for the builds, and only push on builds from master/main?

**Comment by nhejazi** [comment]
My preference would be to append the commit hash to each report PDF, since this will allow for exact tracking of where the reports were generated from. PRs will often contain multiple commits, so appending the commit hash will allow for all successful reports from a given PR to be stored in the `gh-pages` branch.

**Comment by nhejazi** [comment]
I agree that clearing out the `gh-pages` branch each time is a bad idea, especially with multiple open PRs, but I also don't really like the idea of keeping every single successful build. Any thoughts on how to curate what artifacts we keep?

**Comment by thebioengineer** [comment]
Whatever we decide should go into the `contributing.md` so folks know where to look. I can start sketching up a section on CI in the meantime if that is helpful

**Comment by benkeser** [comment]
Simplest route might be just to add the PR number in the commit message to `gh-pages`. Then it doesn't matter if we're overwriting `gh-pages` each time, because one could go through the commit history and find the appropriate build?

**Comment by nhejazi** [comment]
@thebioengineer -- I've started a CI section in the contributing document (https://github.com/CoVPN/correlates_reporting/pull/117/files) but please feel free to edit/review and build on it.

@benkeser -- I think that makes sense. The idea is that Travis committing (via your credentials) would include the PR number in the commit message, which (I think) GitHub will link to the PR automatically, right? If so, that would be a clean way to cross-link `gh-pages` and the PR-specific builds.

**Comment by nhejazi** [comment]
Giving a go to adding the PR number in Travis commits in cfd9731.

**Comment by nhejazi** [comment]
The implemented solution isn’t yet satisfactory — sometimes (I think on merge commits), the environment variable `TRAVIS_PR` is set to false (e.g., https://github.com/CoVPN/correlates_reporting/commit/5cf8890169cea021bd51e49d608b2411ce60898b), leading to the automated commit message being uninformative. This can be resolved by some conditional logic that sets the commit hash in the message instead of the PR number on merge commits.

Additionally, as it was written, the commit messages failed to automatically cross-link to the corresponding PRs (via GitHub’s UI). I think this would be simply resolved by appending a `#` prior to the PR number.

**Comment by nhejazi** [comment]
cross-linking now works as per 234d43d
