### ISSUE TITLE
verification to travis checks

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#219]
As more verification code rolls in and programatic comparisons are implemented, do we want to add these comparisons to the travis build?

On the plus side:
- more robust checks of new code

On the minus side:
- Could slow down merging of PRs if we need to resolve conflicts between programmer and tester

I would probably vote no at this point. But wanted to check with @thebioengineer @nhejazi

**Comment by thebioengineer** [comment]
Verification is usually applied as one of the last checks of data and code quality. My thoughts currently are to get just the verification code together, and outputs verified. Then, since so much updates and changes, make them as programmatic as possible to reduce extra work for the testers. This would include turning them into "make-able" folders that would run the verification code and compare values.

At this time, I would vote no to adding them into the actual Travis build checks, but progressively build up the automation.

**Comment by benkeser** [comment]
The nays carry the day.
