### ISSUE TITLE
cor threshold chapter title

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#365]
<img width="844" alt="Screen Shot 2021-06-03 at 11 19 55 AM" src="https://user-images.githubusercontent.com/17482713/120669713-b30e6600-c45d-11eb-9d38-e1a3582133c9.png">

@Larsvanderlaan, could you please modify the `{# }` heading to get rid of this latex gore?

**Comment by benkeser** [comment]
Also are the axis limits right in this figure? 

<img width="677" alt="Screen Shot 2021-06-03 at 11 24 10 AM" src="https://user-images.githubusercontent.com/17482713/120670294-45af0500-c45e-11eb-8765-6b8f8fe004af.png">

**Comment by Larsvanderlaan** [comment]
Hi David, I've sent a pull request with the title changes.

 I coordinated these axis' with Youyi (based on the get.axis.range functions in _common.R). They look a bit wacky on the mock data but I was told they will look better on the real data.

**Comment by Larsvanderlaan** [comment]
I see that Youyi has similar issues with the "lod" spacing. I believe this is because the axis limits are obtaining by flooring/ceiling the min/max observed values of the marker at the log10 scale. If the observed minimal log10 marker is for example very close to but less than a whole number then the "floor" will add a lot of extra green/white space. 

@youyifong 
Do we want to change the get.axis.range function to prevent this extra space, or do we expect this not to be an issue on the actual data?

**Comment by youyifong** [comment]
In get.range.cor(), we rounded up the max of the marker values and did not
round down lod/2.

We expected some observed values to be lod/2 for the Moderna dataset.

**Comment by benkeser** [comment]
Thanks guys. Let’s leave as is then.
